#!/bin/bash

BASE_URL="https://topszotar.hu/"
WORKING_DIR="$HOME/.szotar"
HIST_DIR="$WORKING_DIR/elozmeny"

WORD="$(printf '' | dmenu -f -p 'Fordítandó:' )"

LETTER=$(echo "${WORD:0:1}" | tr '[:upper:]' '[:lower:]')

[ -d "$WORKING_DIR/$LETTER" ] && \
{ grep -Fxq "$WORD" "$HIST_DIR/$LETTER" && is_new=false || is_new=true; } || \
mkdir "$WORKING_DIR/$LETTER"

$is_new && echo "$WORD" >> "$HIST_DIR/$LETTER" || { cat "$WORKING_DIR/$LETTER/$WORD" | dmenu -l 10; exit 0; }

URL="${BASE_URL}angolmagyar/${WORD}"

result=$(curl -s -L $URL | pup --charset "utf-8" "a.linktootherdict text{}")

[ ! -n "$result" ] && { echo "Nincs találat!" | dmenu; exit 1; }

formatted=$(printf '%s\n' "${result[@]}")

touch "$WORKING_DIR/$LETTER/$WORD" && printf "$formatted" > "$WORKING_DIR/$LETTER/$WORD"

printf "$formatted" | dmenu -l 10
